#! /bin/bash

# This script takes the frame screenshots generated by `fastlane snapshot` and make them into
# screenshots that can be uploaded to the App Store.

# Final screenshot background color
BG_COLOR=#F0F0F0

# Output directory
DIR=screenshots


# iPhone 5.5"

magick -size 1242x2208 xc:$BG_COLOR $DIR/iPhone_5.5_bg.png

magick \
  'screenshots/en-US/iPhone 8 Plus-MainScreen_framed.png' \
  -resize 1241x2208 \
  $DIR/iPhone_5.5_resized.png

magick \
  $DIR/iPhone_5.5_bg.png \
  -colorspace sRGB \
  $DIR/iPhone_5.5_resized.png \
  -gravity center \
  -composite \
  $DIR/iPhone_5.5_final.png

rm $DIR/iPhone_5.5_bg.png $DIR/iPhone_5.5_resized.png



# iPhone 6.7"

magick -size 1290x2796 xc:$BG_COLOR $DIR/iPhone_6.7_bg.png

magick \
  'screenshots/en-US/iPhone 15 Pro Max-MainScreen_framed.png' \
  -resize 1290x2796 \
  $DIR/iPhone_6.7_resized.png

magick \
  $DIR/iPhone_6.7_bg.png \
  -colorspace sRGB \
  $DIR/iPhone_6.7_resized.png \
  -gravity center \
  -composite \
  $DIR/iPhone_6.7_final.png

rm $DIR/iPhone_6.7_bg.png $DIR/iPhone_6.7_resized.png



# iPad 13"

# Make background image that is the same size as the frame image.
magick -size 2350x3132 xc:$BG_COLOR $DIR/iPad_13_bg.png
magick -size 2064x2752 xc:$BG_COLOR $DIR/iPad_13_bg_2.png

# Resizing because the screenshot from the simulator is slightly larger than the frame content area.
#
# screenshot: 2064 x 2752
# Frame content area: 2048 x 2732
magick \
  './screenshots/en-US/iPad Pro 13-inch (M4)-MainScreen.png' \
  -resize 2048x2732 \
  $DIR/ipad_13_resized.png


# Make the screenshot the same size as the frame image.
magick \
  $DIR/iPad_13_bg.png \
  -colorspace sRGB \
  $DIR/ipad_13_resized.png \
  -gravity center \
  -composite \
  $DIR/ipad_13_padded.png

# Overlay the frame image on top of the screenshot to produce the framed image.
magick \
  $DIR/ipad_13_padded.png \
  './frames/ipad_pro_13.png' \
  -gravity center \
  -composite \
  $DIR/ipad_13_framed.png

# Resize to produce final image
magick \
  $DIR/ipad_13_framed.png \
  -resize 2064x2752 \
  $DIR/ipad_13_resized_2.png

# Pad 1 pixel vertically
magick \
  $DIR/iPad_13_bg_2.png \
  -colorspace sRGB \
  $DIR/ipad_13_resized_2.png \
  -gravity center \
  -composite \
  $DIR/ipad_13_final.png

# Delete temporary images
rm $DIR/iPad_13_bg.png \
   $DIR/iPad_13_bg_2.png \
   $DIR/ipad_13_resized.png \
   $DIR/ipad_13_padded.png \
   $DIR/ipad_13_framed.png \
   $DIR/ipad_13_resized_2.png


# # iPad 12.9"

# magick -size 2048x2732 xc:$BG_COLOR $DIR/iPad_12.9_bg.png

# magick \
#   'screenshots/en-US/iPhone 15 Pro Max-MainScreen_framed.png' \
#   -resize 2048x2732 \
#   $DIR/iPad_12.9_resized.png

# magick \
#   $DIR/iPad_12.9_bg.png \
#   -colorspace sRGB \
#   $DIR/iPad_12.9_resized.png \
#   -gravity center \
#   -composite \
#   $DIR/iPad_12.9_final.png

# rm $DIR/iPad_12.9_bg.png $DIR/iPad_12.9_resized.png
